import React from 'react';
import { Link } from 'react-router-dom';
import { Navbar } from '../components';

const Attributions = () => {
  return (
    <>
      <Navbar />
      <div className="bg-flashWhite min-h-screen py-16">
        <div className="container mx-auto px-4">
          <h1 className="text-4xl font-bold text-eerieBlack mb-8">Attributions</h1>
          <div className="bg-white shadow-md rounded p-6 text-eerieBlack">
            <h2 className="text-2xl font-semibold mb-4">Template</h2>
            <p className="mb-4">
              Original template created by <a href="https://github.com/shaqdeff" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Shaquille Ndunda</a>. The template is available at <a href="https://github.com/shaqdeff/Portfolio-Template" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">https://github.com/shaqdeff/Portfolio-Template</a>. Modified and customized by Ethan Martinez, including changes to images, icons, layout, and the addition of new components.
            </p>

            <h2 className="text-2xl font-semibold mb-4">Icons</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                Education icons created by <a href="https://www.flaticon.com/free-icons/education" target="_blank" rel="noopener noreferrer" title="education icons" className="text-french hover:text-battleGray transition duration-300">Freepik - Flaticon</a>
              </li>
              <li>
                Play icons created by <a href="https://www.flaticon.com/free-icons/play" target="_blank" rel="noopener noreferrer" title="play icons" className="text-french hover:text-battleGray transition duration-300">Freepik - Flaticon</a>
              </li>
              <li>
                LinkedIn icon by <a href="https://icons8.com/icon/8808/linkedin" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Icons8</a>
              </li>
              <li>
                Github icons created by <a href="https://brand.github.com/foundations/logo" target="_blank" rel="noopener noreferrer" title="github icons" className="text-french hover:text-battleGray transition duration-300">Github</a>
              </li>
              <li>
                SQL icon by <a href="https://icons8.com/icon/3767/sql" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Icons8</a>
              </li>
              <li>
                C++ icon by <a href="https://icons8.com/icon/55199/c%2B%2B" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Icons8</a>
              </li>
              <li>
                Swift icon by <a href="https://icons8.com/icon/24464/swift" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Icons8</a>
              </li>
              <li>
                Nodejs icon by <a href="https://icons8.com/icon/t9oCxEN7McHZ/nodejs" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Icons8</a>
              </li>
              <li>
                Python icon by <a href="https://icons8.com/icon/12592/python" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Icons8</a>
              </li>
            </ul>

            <h2 className="text-2xl font-semibold mb-4 mt-6">Images</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>
                Background image for the 'Technologies' section by <a href="https://www.pexels.com/@eric-thurber-2062658/" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Eric Thurber</a> from <a href="https://www.pexels.com/photo/time-lapse-photo-of-city-during-night-3688579/" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">Pexels</a>
              </li>
              <li>
                Image featured in 'Hero' section is 'Glowing spider web on dark abstract backdrop generated by AI' by <a href="https://www.freepik.com/free-ai-image/glowing-spider-web-dark-abstract-backdrop-generated-by-ai_42586726.htm#query=black%20white%20technology&position=4&from_view=keyword&track=ais_hybrid&uuid=089d5df9-6748-4a6a-b786-d3392bdc5fec" target="_blank" rel="noopener noreferrer" className="text-french hover:text-battleGray transition duration-300">vecstock on Freepik</a>
              </li>
            </ul>
          </div>
          <Link to="/" className="mt-8 inline-block text-french hover:text-battleGray transition duration-300">
            ← Back to Home
          </Link>
        </div>
      </div>
    </>
  );
};

export default Attributions;